apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: car-value-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: car-value-service
  minReplicas: 2      # Start with 2 pods minimum
  maxReplicas: 8      # Scale up to 8 pods maximum
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale when CPU hits 70%
