apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: review-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: review-service
 minReplicas: 10      # Start with 10 pods minimum
 maxReplicas: 25      # Scale up to 25 pods maximum
 metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 50  # Scale when CPU hits 50%