apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-value-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-value-service
  template:
    metadata:
      labels:
        app: car-value-service
    spec:
      containers:
      - name: car-value-service
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/car-value-service:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: car-value-service
spec:
  selector:
    app: car-value-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP